name: Deploy FastAPI on AWS

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin    

      - name: Build Docker Image
        run: docker build -t abhinavdogra003768/llm .

      - name: Publish Image to Docker Hub
        run: docker push abhinavdogra003768/llm:latest 

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into AWS & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Navigate to the app directory (Ensure this path is correct)
            cd /home/ubuntu/my-fastapi-app

            # Pull the latest changes
            git pull origin main

            # Pull latest Docker image
            docker pull abhinavdogra003768/llm:latest 

            # Stop and remove old container if it exists
            docker stop llm-container || true
            docker rm llm-container || true

            # Cleanup unused Docker images
            docker system prune -f

            # Run the new container
            docker run -d -p 8000:8000 --name llm-container abhinavdogra003768/llm:latest

            # Show running containers
            docker ps
