name: Deploy Python LLM API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin    

      - name: Build Docker Image
        run: docker build -t mydockerhubuser/my-llm-app .

      - name: Push Image to Docker Hub
        run: docker push mydockerhubuser/my-llm-app:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Ensure an EC2 runner is set up
    steps:
      - name: Pull Latest Docker Image
        run: docker pull mydockerhubuser/my-llm-app:latest

      - name: Stop Old Container
        run: docker rm -f llm-container || true

      - name: Cleanup Docker
        run: docker system prune -f

      - name: Run New Container with GPU Support
        run: |
          docker run -d --gpus all -p 8000:8000 -p 11434:11434 --restart unless-stopped --name llm-container \
            mydockerhubuser/my-llm-app:latest
