name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin    

      - name: Build Docker Image
        run: docker build -t abhinavdogra003768/llm .

      - name: Publish Image to Docker Hub
        run: docker push abhinavdogra003768/llm:latest 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull latest image from Docker Hub
        run: docker pull abhinavdogra003768/llm:latest 

      - name: Remove old container
        run: docker rm -f llm-container || true  

      - name: Cleanup unused images
        run: docker system prune -f

      - name: Run new Docker Container
        run: |
          docker run -d --restart unless-stopped -p 8000:8000 --name llm-container \
            abhinavdogra003768/llm:latest






