name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest Docker image
        run: |
          docker pull abhinavdogra003768/llm:latest

      - name: Stop and remove existing container (if running)
        run: |
          docker stop llm-container || true
          docker rm llm-container || true

      - name: Run the new container
        run: |
          docker run -d --name llm-container -p 8000:8000 abhinavdogra003768/llm:latest
