name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run Docker container
        run: |
          docker build -t my-python-app .
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker run -d --name my-python-app -p 8000:8000 my-python-app
